<?php
  /**
   *
   */
  class Report
  {

    function __construct()
    {
      // echo json_encode($data);
      // die;
      date_default_timezone_set('Asia/Manila');
      $this->page = 1;
      $this->totalPage = 1;
      $this->date_today = date('F d, Y H:i:s');
      $this->generated_by = '';
      $this->file_name = $this->date_today;
      $this->category = '';
      $this->report_type = '';
      $this->report_date = '';
      $this->items_per_page = 23;
      $this->total_items = 0;
      $this->data = [];
      $this->pdf = new FPDF('L');
    }

    private function _initpdf(){
      $this->totalPage = ceil($this->total_items / $this->items_per_page) == 0 ? 1 : ceil($this->total_items / $this->items_per_page);
      $this->pdf->AddFont('Calibri','','Calibri.php');
      $this->pdf->AddFont('BodoniMTBlack','B','BodoniMTBlack.php');
      $this->pdf->AddFont('Calibri Bold','B','Calibri Bold.php');
      $this->pdf->SetMargins(5, 0, 0);
    }

    private function _headerInfo(){
      $this->pdf->setY(35);
      $this->pdf->SetFont('Calibri','',12);
      $this->pdf->Cell(0,4,$this->category.' REPORT',0,1,'C',false);
      $this->pdf->setXY(20,45);
      $this->pdf->SetFont('Calibri Bold','B',12);
      $this->pdf->Cell(25,2,'TYPE : ',0,0,'L',false);
      $this->pdf->SetFont('Calibri','',12);
      $this->pdf->Cell(20,2,$this->report_type,0,1,'L',false);
      $this->pdf->SetFont('Calibri Bold','B',12);
      $this->pdf->setXY(20,50);
      $this->pdf->Cell(25,2,'DATE : ',0,0,'L',false);
      $this->pdf->SetFont('Calibri','',12);
      $this->pdf->Cell(20,2,$this->report_date,0,1,'L',false);
      $this->pdf->SetFont('Calibri Bold','B',12);
    }

    private function _createHeader(){
      $this->pdf->AddPage();
      $this->pdf->Image("public/img/SAMSUNG LOGO.png", 120, 2, 60);
      $this->pdf->setY(20);
      $this->pdf->SetFont('Calibri Bold','B',12);
      $this->pdf->Cell(0,4,'SABSUNG PHILIPPINES',0,1,'C',false);
      $this->pdf->SetFont('Calibri','',11);
      $this->pdf->SetTextColor(92,92,92);
      $this->pdf->Cell(0,4,'#342 Brgy. Tibay, Makati City, Philippines',0,1,'C',false);
      $this->pdf->Cell(0,4,'(632) 335-1787 or 335-1777 local 293',0,1,'C',false);
      $this->pdf->SetTextColor(0,0,0);
      $this->pdf->setXY(275,6);
      $this->pdf->Cell(10,2,'Page '.$this->page.'/'.$this->totalPage,0,1,'C',false);
      $this->_headerInfo();
    }
    private function _createFooter($items, $total){
      $this->pdf->SetAutoPageBreak(true,1);
      $this->pdf->setY(197);
      $this->pdf->SetFont('Calibri','',12);
      $this->pdf->Cell(70,4,'Generated By: '.$this->generated_by,0,0,'L',false);
      $this->pdf->Cell(70,4,'Date & Time: '.$this->date_today,0,0,'C',false);
      $this->pdf->Cell(70,4,'Number of Transaction: '.$items,0,1,'R',false);
      $this->pdf->setXY(250, 197);
      $this->pdf->SetFont('Calibri Bold','B',12);
      $this->pdf->Cell(84,4,'Total: '.number_format($total,2),0,1,'L',false);
    }

    private function _bodyHeaders(){
      $this->pdf->setY(60);
      $this->pdf->SetFont('Calibri Bold','B',11);
      $this->pdf->Cell(10,5,'REQ.','TL',0,'C',false);
      $this->pdf->Cell(30,5,'TRANSACTION','TL',0,'C',false);
      $this->pdf->Cell(50,5,'','TL',0,'C',false);
      $this->pdf->Cell(102,5,'ITEMS','TBL',0,'C',false);
      $this->pdf->Cell(42,5,'DATE',1,0,'C',false);
      $this->pdf->Cell(20,5,'DELIVERY','TL',0,'C',false);
      $this->pdf->Cell(30,5,'','TLR',1,'C',false);

      $this->pdf->Cell(10,5,'NUM','BL',0,'C',false);
      $this->pdf->Cell(30,5,'NUMBER','BL',0,'C',false);
      $this->pdf->Cell(50,5,'CLIENT NAME','BL',0,'C',false);
      $this->pdf->Cell(68,5,'PRODUCT NAME','BL',0,'C',false);
      $this->pdf->Cell(23,5,'PRICE','BL',0,'C',false);
      $this->pdf->Cell(11,5,'QTY','BL',0,'C',false);
      $this->pdf->Cell(21,5,'PLACEMENT',1,0,'C',false);
      $this->pdf->Cell(21,5,'DELIVERED',1,0,'C',false);
      $this->pdf->Cell(20,5,'FEE','BL',0,'C',false);
      $this->pdf->Cell(30,5,'TOTAL','BLR',1,'C',false);
    }

    private function _bodyData($row, $data){
      $delivery = count($data['items']) > 2 ? 100.00 : 300.00;
      for ($x=0; $x < count($data['items']); $x++) {
        if ($x == 0 && count($data['items'])-1 != $x) {
          $this->pdf->SetFont('Calibri','',10);
          $this->pdf->Cell(10,5,$row,'L',0,'C',false);
          $this->pdf->Cell(30,5,'#'.$data['transaction_id'],'L',0,'C',false);
          $this->pdf->Cell(50,5,$data['user'],'L',0,'C',false);
          $this->pdf->Cell(68,5,$data['items'][$x]['name'],'L',0,'L',false);
          $this->pdf->Cell(23,5,number_format($data['items'][$x]['price'],2),'L',0,'C',false);
          $this->pdf->Cell(11,5,$data['items'][$x]['quantity'],'L',0,'C',false);
          $this->pdf->Cell(21,5,explode(' ', $data['date'])[0],'L',0,'C',false);
          $this->pdf->Cell(21,5,$data['status_date'],'L',0,'C',false);
          $this->pdf->Cell(20,5,number_format($delivery,2),'L',0,'C',false);
          $this->pdf->Cell(30,5,number_format(($data['total'] + $delivery),2),'LR',1,'C',false);
        }elseif ($x != count($data['items'])-1) {
          $this->pdf->SetFont('Calibri','',10);
          $this->pdf->Cell(10,5,'','L',0,'C',false);
          $this->pdf->Cell(30,5,'','L',0,'C',false);
          $this->pdf->Cell(50,5,'','L',0,'C',false);
          $this->pdf->Cell(68,5,$data['items'][$x]['name'],'L',0,'L',false);
          $this->pdf->Cell(23,5,number_format($data['items'][$x]['price'],2),'L',0,'C',false);
          $this->pdf->Cell(11,5,$data['items'][$x]['quantity'],'L',0,'C',false);
          $this->pdf->Cell(21,5,'','L',0,'C',false);
          $this->pdf->Cell(21,5,'','L',0,'C',false);
          $this->pdf->Cell(20,5,'','L',0,'C',false);
          $this->pdf->Cell(30,5,'','LR',1,'C',false);
        }else {
          if (count($data['items']) == 1) {
            $this->pdf->SetFont('Calibri','',10);
            $this->pdf->Cell(10,5,$row,'BL',0,'C',false);
            $this->pdf->Cell(30,5,'#'.$data['transaction_id'],'BL',0,'C',false);
            $this->pdf->Cell(50,5,$data['user'],'BL',0,'C',false);
            $this->pdf->Cell(68,5,$data['items'][$x]['name'],'BL',0,'BL',false);
            $this->pdf->Cell(23,5,number_format($data['items'][$x]['price'],2),'BL',0,'C',false);
            $this->pdf->Cell(11,5,$data['items'][$x]['quantity'],'BL',0,'C',false);
            $this->pdf->Cell(21,5,explode(' ', $data['date'])[0],'BL',0,'C',false);
            $this->pdf->Cell(21,5,$data['status_date'],'BL',0,'C',false);
            $this->pdf->Cell(20,5,number_format($delivery,2),'BL',0,'C',false);
            $this->pdf->Cell(30,5,number_format(($data['total'] + $delivery),2),'BLR',1,'C',false);
          }else {
            $this->pdf->SetFont('Calibri','',10);
            $this->pdf->Cell(10,5,'','BL',0,'C',false);
            $this->pdf->Cell(30,5,'','BL',0,'C',false);
            $this->pdf->Cell(50,5,'','BL',0,'C',false);
            $this->pdf->Cell(68,5,$data['items'][$x]['name'],'BL',0,'L',false);
            $this->pdf->Cell(23,5,number_format($data['items'][$x]['price'],2),'BL',0,'C',false);
            $this->pdf->Cell(11,5,$data['items'][$x]['quantity'],'BL',0,'C',false);
            $this->pdf->Cell(21,5,'','BL',0,'C',false);
            $this->pdf->Cell(21,5,'','BL',0,'C',false);
            $this->pdf->Cell(20,5,'','BL',0,'C',false);
            $this->pdf->Cell(30,5,'','BLR',1,'C',false);
          }
        }
      }
      return $data['total'] + $delivery;
    }

    private function _createBody(){
      $this->_bodyHeaders();
      $row = 0;
      $total = 0;
      $count = 0;
      if (count($this->data) > 0) {
        $this->pdf->setY(70);
        for ($i=0; $i < count($this->data) ; $i++) {
          $row += count($this->data[$i]['items']);
          if ($row > $this->items_per_page) {
            $this->_createFooter($count, $total);
            $this->page++;
            $this->_createHeader();
            $this->_bodyHeaders();
            $row = 0;
            $total = 0;
            $count = 0;
          }
          $count++;
          $total += $this->_bodyData($count, $this->data[$i]);
        }
        $this->_createFooter($count, $total);
      }else {
        $this->pdf->SetFont('Calibri','',14);
        $this->pdf->setY(120);
        $this->pdf->Cell(0,5,'NO RECORDS TO SHOW',0,0,'C',false);
      }
    }

    public function generate(){
      $this->_initpdf();
      $this->_createHeader();
      $this->_createBody();
      $this->pdf->output('I', $this->file_name.".pdf");
    }

  }
